packages:
  - apps/*
  - exmaples/*
  - packages/*
  - tools/*

catalog:
  "@arkenv/vite-plugin": ^0.0.32
  "@cloudflare/kumo": ^1.12.1
  "@cloudflare/vite-plugin": ^1.28.0
  "@cloudflare/workers-types": ^4.20260313.1
  "@hono/oauth-providers": ^0.8.5
  "@octokit/app": ^16.1.2
  "@phosphor-icons/react": ^2.1.10
  "@tailwindcss/vite": ^4.2.1
  "@tanstack/react-router": ^1.167.0
  "@types/node": ^24
  agents: ^0.7.6
  arkenv: ^0.11.0
  arktype: ^2.2.0
  effect: 4.0.0-beta.31
  hono: ^4.12.8
  tailwindcss: ^4.2.1
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-react-click-to-component: ^4.2.0
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: ^4.73.0

catalogMode: prefer

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - sharp
  - workerd

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
